color=[]
color1=input("첫 번째 색을 입력하시오")
color.append(color1)
color2=input("두 번째 색을 입력하시오")
color.append(color2)
color3=input("세 번째 색을 입력하시오")
color.append(color3)
color4=input("네 번째 색을 입력하시오")
color.append(color4)
import turtle
turtle.shape("turtle")
turtle.fillcolor(color[0])
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.forward(50)
turtle.fillcolor(color[1])
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.forward(50)
turtle.fillcolor(color[2])
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.forward(50)
turtle.fillcolor(color[3])
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.done()